### ISSUE TITLE
inconsistency in usage of usb_start_receive_ep0_data_stage()

### ISSUE THREAD

**Issue by hughsie** [signal11/m-stack#10]
In the various programs in m-stack there are two different ways usb_start_receive_ep0_data_stage() is being used:

    usb_start_receive_ep0_data_stage(buf,len,func_cb,userdata);

and

    usb_start_receive_ep0_data_stage(buf,len,&func_cb,userdata);

I don't *think* it matters to the xc8 compiler, but it does feel a bit odd to rely on this undocumented compiler quirk.

Richard

**Comment by signal11** [comment]
It's not an undocumented quirk, it's C. Both are correct. Remember also that m-stack works on more than just xc8.

See the first few links at:
https://www.google.com/search?q=ampersand+function+pointer

**Comment by hughsie** [comment]
Hah, I've learned something new today. Sorry for the noise! :)

**Comment by signal11** [comment]
No worries
