### ISSUE TITLE
buffer_descriptor oddities when compiling on standard mipsel-none-elf toolchain

### ISSUE THREAD

**Issue by etherealvisage** [signal11/m-stack#14]
Hi,

I'm trying to get m-stack working on a standard mipsel GCC variant. (I understand that only Microchip's XC32 is officially supported, but I'm willing to put in the effort to get it ported to my current dev environment.) The one thing that I'm currently struggling to understand is the following structure from `usb_hal.h`: (starts on line 390)

```C
struct buffer_descriptor {
	union {
		struct {
			/* When receiving from the SIE. (USB Mode) */
			uint16_t BC : 10;
			uint16_t PID : 4; /* See enum PID */
			uint16_t DTS: 1;
			uint16_t UOWN : 1;
		};
		struct {
			/* When giving to the SIE (CPU Mode) */
			uint16_t /*BC*/ : 10;
			uint16_t BSTALL : 1;
			uint16_t DTSEN : 1;
			uint16_t reserved : 2;
			uint16_t DTS : 1;
			uint16_t /*UOWN*/ : 1;
		};
		struct {
			uint8_t BDnSTAT_lsb;
			uint8_t BDnSTAT; /* High byte, where the flags are */
		};
		uint16_t BDnSTAT_CNT; /* BDnSTAT and BDnCNT as a 16-bit */
	}STAT;
	BDNADR_TYPE BDnADR;
};
```

First, there's two members in the `STAT` union that have the name `DTS`, which is why my GCC compiler is complaining right now. While trying to make sense of this, I ran across the second thing, which is: according to the datasheet for the PIC32MX series (I'm referring to the [MX460](http://ww1.microchip.com/downloads/en/DeviceDoc/PIC32MX_Datasheet_v2_61143B.pdf) datasheet for now, though the same is the case for the MX250. I don't have a link handy but the structure looks identical), the structure is [64 bits in total](http://imgur.com/V3lZG74), because there's padding between `BCOUNT` and the other bits, which doesn't appear to be reflected in the `buffer_descriptor` definition.

What am I missing?

Thank you!

- ethereal

**Comment by signal11** [comment]
> I'm trying to get m-stack working on a standard mipsel GCC variant.

Great! I'm interested in this.

> First, there's two members in the STAT union that have the name DTS, which is why my GCC compiler is complaining right now.

Comment one out. They're in the same position in the struct. Remember there's a union involved.

> While trying to make sense of this, I ran across the second thing, which is: according to the datasheet for the PIC32MX series ... , the structure is 64 bits in total, because there's padding between BCOUNT and the other bits, which doesn't appear to be reflected in the buffer_descriptor definition.

You're looking at the struct for 16-bit chips. Look at the ifdef __XC32__ section.

**Comment by etherealvisage** [comment]
> Comment one out. They're in the same position in the struct. Remember there's a union involved.

Surprised that XC32 doesn't complain about this, but I guess Microchip has done weird things in the past... no reason to expect that would change.

> You're looking at the struct for 16-bit chips. Look at the ifdef __XC32__ section.

That makes way more sense. I think I got confused between switching between my editor and the GitHub repository browser somewhere along the lines... thanks!

**Comment by signal11** [comment]
> Surprised that XC32 doesn't complain about this, but I guess Microchip has done weird things in the past... no reason to expect that would change.

It could be simply that XC32 is older version of GCC that allowed it (because it knew both bits were actually the same). I'm guessing it was removed in later versions because it's probably not standards compliant. That's all just conjecture on my part, but it's a possibility.

>  I think I got confused between switching between my editor and the GitHub repository browser somewhere along the lines...

Incidentally MPLABX has in the past had problems greying out the wrong sections of #ifdef code in M-Stack, so it's not just you :)

**Comment by etherealvisage** [comment]
Just a quick update — I now have M-stack working on a custom board with a PIC32MX250F128B.

I've had to make a couple of very minor modifications to get things working, but overall it has been quite minor. I'll create a pull request once I've cleaned up the changes.

Thank you! This has saved me a huge amount of effort.

- ethereal
